# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20181118_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='content2',
        ),
    ]
