# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_auto_20181228_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileManger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
