# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-01 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_userprofilemanger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileManger',
        ),
    ]
